# Site settings
title: CPPDUG
email: cppdug-list@meetup.com
description: > # this means to ignore newlines until "baseurl:"
  Dublin C/C++ User Group
url: "https://cppdug.github.io" # the base hostname & protocol for your site
twitter_username: cppdug
github_username:  cppdug

theme: jekyll-theme-slate