# Site settings
title: CPPDUG
email: cppdug-list@meetup.com
description: > # this means to ignore newlines until "baseurl:"
  Dublin C/C++ User Group
url: "https://cppdug.github.io" # the base hostname & protocol for your site
twitter_username: cppdug
github_username: cppdug

owner_name: "The CPPDUG Organisers"
owner_url: "https://www.meetup.com/cppdug/members/?op=leaders"

theme: jekyll-theme-slate